version: "3"

services:
  selfie-records:
    build:
      context: ./2_app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./2_app/src:/app/src
    restart: always
